// Generates iOS launch (splash) screens for the installed standalone PWA.
//
// iOS shows an `apple-touch-startup-image` on COLD LAUNCH of the home-screen app,
// matched to the device by a media query. Each device + orientation needs its own
// image at exact device pixels (css size * devicePixelRatio).
//
// Outputs PNGs to public/icons/splash/ and prints the <link> block for index.html.
//
// Run with: npm run splash
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mkdir } from 'node:fs/promises';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'public', 'icons', 'icon-192x192.svg');
const OUT_DIR = join(ROOT, 'public', 'icons', 'splash');

// Matches manifest background_color so the splash blends into the app boot.
const BG = '#0f0f0f';

// Broad device matrix: [label, cssWidth, cssHeight (portrait), devicePixelRatio].
// Portrait + landscape variants are emitted for each.
const DEVICES = [
  // iPhones
  ['iphone-se',          320, 568, 2], // SE 1st gen / 5
  ['iphone-8',           375, 667, 2], // 6/7/8/SE2/SE3
  ['iphone-8-plus',      414, 736, 3], // 6+/7+/8+
  ['iphone-x',           375, 812, 3], // X/XS/11 Pro/12 mini/13 mini
  ['iphone-xr',          414, 896, 2], // XR/11
  ['iphone-xs-max',      414, 896, 3], // XS Max/11 Pro Max
  ['iphone-12',          390, 844, 3], // 12/13/14
  ['iphone-12-pro-max',  428, 926, 3], // 12/13 Pro Max, 14 Plus
  ['iphone-14-pro',      393, 852, 3], // 14 Pro/15/16
  ['iphone-14-pro-max',  430, 932, 3], // 14 Pro Max/15 Plus/15 Pro Max/16 Plus
  // iPads (css points, dpr 2)
  ['ipad-mini',          768, 1024, 2], // mini / 9.7
  ['ipad-10_2',          810, 1080, 2], // 10.2
  ['ipad-air',           820, 1180, 2], // Air 10.9
  ['ipad-pro-11',        834, 1194, 2], // Pro 11 / Air
  ['ipad-pro-10_5',      834, 1112, 2], // Pro 10.5
  ['ipad-pro-12_9',     1024, 1366, 2], // Pro 12.9
];

async function renderSplash(wPx, hPx, outName) {
  // Logo sized to ~30% of the smaller dimension, centered on the background.
  const logo = Math.round(Math.min(wPx, hPx) * 0.3);
  const art = await sharp(SRC, { density: 384 })
    .resize(logo, logo, { fit: 'contain', background: BG })
    .png()
    .toBuffer();

  const left = Math.round((wPx - logo) / 2);
  const top = Math.round((hPx - logo) / 2);

  await sharp({ create: { width: wPx, height: hPx, channels: 3, background: BG } })
    .composite([{ input: art, top, left }])
    .flatten({ background: BG })
    .png()
    .toFile(join(OUT_DIR, outName));
}

function linkTag(fileName, wCss, hCss, dpr, orientation) {
  const media =
    `(device-width: ${wCss}px) and (device-height: ${hCss}px) ` +
    `and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: ${orientation})`;
  return `    <link rel="apple-touch-startup-image" media="${media}" href="/icons/splash/${fileName}" />`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const links = [];
  let count = 0;

  for (const [label, cssW, cssH, dpr] of DEVICES) {
    // Portrait
    const pName = `${label}-portrait.png`;
    await renderSplash(cssW * dpr, cssH * dpr, pName);
    links.push(linkTag(pName, cssW, cssH, dpr, 'portrait'));
    count++;

    // Landscape (swap css width/height; image dimensions swap too)
    const lName = `${label}-landscape.png`;
    await renderSplash(cssH * dpr, cssW * dpr, lName);
    links.push(linkTag(lName, cssH, cssW, dpr, 'landscape'));
    count++;
  }

  console.log(`Generated ${count} splash images in public/icons/splash/.\n`);
  console.log('--- Paste this block into index.html <head> ---\n');
  console.log('    <!-- iOS launch screens (generated by scripts/generate-splash.mjs) -->');
  console.log(links.join('\n'));
  console.log('\n--- end block ---');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
